language: python
python:
  - "2.7"
  - "3.4"

cache: pip

addons:
  apt:
    packages:
    - python-pip
    - python-numpy
    - python-scipy

install:
  - pip install coveralls
  - pip install matplotlib
  - python setup.py install

script: 
  - nosetests -w tests
  - coverage run --source=pysyzygy setup.py test

after_success:
  - coveralls