# Adapted from dfm/george

language: python

# blocklist
branches:
  except:
  - nick
  - nick_dev

matrix:
  include:
    # All the versions of Python.
    - python: 2.7
    - python: 3.4

cache: pip

addons:
  apt:
    packages:
    - libeigen3-dev

# We will pip install pysyzygy and k2plr
git:
    submodules: false

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  
install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --yes numpy scipy matplotlib nose pip astropy six statsmodels scikit-learn 
  - pip install coveralls astroML astroML_addons george==0.2.1 pysyzygy k2plr
  - python setup.py develop

script: 
  - nosetests --with-coverage --cover-package=everest -v -w tests

after_success:
  - coveralls
