language: python
python:
  - "2.7"
  - "3.4"

cache: pip

addons:
  apt:
    packages:
    - python-pip
    - libeigen3-dev
    - python-numpy
    - python-scipy

before_install:
  - pip install george

install:
  - python setup.py install

script: nosetests -w tests

after_success:
  - coveralls